import { NextSeo } from "next-seo";
import { PageGridItem, withGrid } from "../../components/grid";
import Layout from "../../components/layout";
import PageHeader from "../../components/page-header";

import { getFooterMenu } from "../../lib/Menus";
import { getLatestPages } from "../../lib/Pages";

export default function PageListTemplate({ menuItems, pages }) {
  const PagesGrid = withGrid(PageGridItem);

  return (
    <Layout footerMenu={menuItems}>
      <NextSeo
        title="Decoupled Next WordPress Demo"
        description="Generated by create next app."
      />
      <PageHeader title="Pages" />
      <h1 class="text-6xl font-normal leading-normal mt-0 mb-2 text-pink-800">
        Hello
      </h1>
      <section>
        <PagesGrid contentType="pages" data={pages} />
      </section>
    </Layout>
  );
}

export async function getStaticProps() {
  const menuItems = await getFooterMenu();
  const pages = await getLatestPages();

  return {
    props: {
      menuItems,
      pages,
    },
  };
}
