name: 'Starter Split and Changesets'

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    name: version and publish
    env:
      CI: true
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
# Checkout the repo and setup pnpm
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Setup npmrc
        run:
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >
          .npmrc
      - name: install dependencies
        run: pnpm install
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'Update versions'
          title: 'Update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  packages_split:
    # only run this job after release have finished
    needs: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        include:
          - local_path: 'starters/gatsby-wordpress-starter'
            split_repository: 'gatsby-wordpress-starter'
          - local_path: 'starters/next-drupal-starter'
            split_repository: 'next-drupal-starter'
          - local_path: 'starters/next-wordpress-starter'
            split_repository: 'next-wordpress-starter'
            # docs site
          - local_path: 'web'
            split_repository: 'decoupled-kit-docs'
    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.1'
        with:
          # ↓ split <local_path> directory
          package_directory: '${{ matrix.local_path }}'

          # ↓ into https://github.com/org/split_repository repository
          repository_organization: 'pantheon-systems'
          repository_name: '${{ matrix.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: 'brian-ci'
          user_email: 'brian.perry@pantheon.io'

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.1'
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: '${{ matrix.local_path }}'

          repository_organization: 'pantheon-systems'
          repository_name: '${{ matrix.split_repository }}'

          # ↓ the user signed under the split commit
          user_name: 'brian-ci'
          user_email: 'brian.perry@pantheon.io'
